name: Feature Request
description: Suggest an idea for this project
body:
  - type: input
    attributes:
      label: Snipe-IT Version
    validations:
      required: true
  - type: input
    id: server_operatingSystem
    attributes:
      label: Operating System
      description: 'e.g. Ubuntu, Windows'
    validations:
      required: true
  - type: input
    attributes:
      label: Web Server
      description: 'e.g. Apache, IIS'
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context Add any other context or screenshots about the feature request here.
